# Generated by Django 2.1.3 on 2018-11-06 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('square_feet', models.IntegerField()),
                ('main_img', models.ImageField(upload_to='media/imgs/')),
                ('img_1', models.ImageField(blank=True, upload_to='media/imgs/')),
                ('img_2', models.ImageField(blank=True, upload_to='media/imgs/')),
                ('img_3', models.ImageField(blank=True, upload_to='media/imgs/')),
                ('img_4', models.ImageField(blank=True, upload_to='media/imgs/')),
                ('img_5', models.ImageField(blank=True, upload_to='media/imgs/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
