# Generated by Django 2.1.3 on 2018-11-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='paid_fee',
            field=models.BooleanField(default=False),
        ),
    ]
