# Generated by Django 2.1.3 on 2018-11-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20181107_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img_1',
            field=models.ImageField(blank=True, upload_to='imgs/others/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img_2',
            field=models.ImageField(blank=True, upload_to='imgs/others/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img_3',
            field=models.ImageField(blank=True, upload_to='imgs/others/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img_4',
            field=models.ImageField(blank=True, upload_to='imgs/others/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img_5',
            field=models.ImageField(blank=True, upload_to='imgs/others/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='main_img',
            field=models.ImageField(upload_to='imgs/main/%Y/%m/%d/'),
        ),
    ]
