# Generated by Django 2.1.3 on 2018-11-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20181129_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
