# Generated by Django 2.1.3 on 2018-11-06 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='media/imgs/')),
                ('phone', models.IntegerField(blank=True)),
                ('is_seller', models.BooleanField(default=False)),
                ('joined', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
