# Generated by Django 2.1.3 on 2018-11-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181112_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_seller',
            new_name='terms',
        ),
    ]
