# Generated by Django 2.1.3 on 2018-11-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_auto_20181114_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='enquire',
            field=models.CharField(choices=[('general_message', 'General Message'), ('property', 'Property Enquire'), ('feedback', 'Feedback'), ('other', 'Anything else')], default='general_message', max_length=50),
        ),
    ]
