# Generated by Django 2.1.3 on 2018-11-15 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_contactmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='posted',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
