# Generated by Django 2.1.3 on 2018-11-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_contactmessage_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='user',
            field=models.EmailField(blank=True, max_length=250),
        ),
    ]
