# Generated by Django 2.1.3 on 2018-11-15 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0006_auto_20181115_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='user',
        ),
    ]
